### ISSUE TITLE
Documentation: Math rendering

### ISSUE THREAD

**Issue by elbeejay** [passaH2O/dorado#42]
Looks like the math rendering isn't working as it should be, should be a simple fix to change the LaTeX engine for Sphinx in `conf.py` (hopefully).

<img width="948" alt="image" src="https://github.com/passaH2O/dorado/assets/1770513/b63ae0d1-d673-44a7-9cc4-d33a043eeef1">

**Comment by wrightky** [comment]
Equations in docs are working now, considering this successful
